/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my_company.memoria.jogador;

import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author pinhe
 */
public class EsperaJogo extends javax.swing.JPanel {
    private final MenuCliente menu;

    /**
     * Creates new form EsperaJogo
     * @param menu
     */
    public EsperaJogo(MenuCliente menu) {
        this.menu = menu;
        initComponents();
        jogadoresPanel.setLayout(new BoxLayout(jogadoresPanel, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTempoDeEspera = new javax.swing.JLabel();
        textFieldTempoDeEspera = new javax.swing.JTextField();
        comecarBotao = new javax.swing.JButton();
        jogadoresPanel = new javax.swing.JPanel();

        labelTempoDeEspera.setText("Setar Tempo de Espera (segundos):");

        textFieldTempoDeEspera.setText("3");

        comecarBotao.setText("Começar Jogo");
        comecarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comecarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jogadoresPanelLayout = new javax.swing.GroupLayout(jogadoresPanel);
        jogadoresPanel.setLayout(jogadoresPanelLayout);
        jogadoresPanelLayout.setHorizontalGroup(
            jogadoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jogadoresPanelLayout.setVerticalGroup(
            jogadoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jogadoresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTempoDeEspera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldTempoDeEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(comecarBotao)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempoDeEspera)
                    .addComponent(textFieldTempoDeEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogadoresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comecarBotao)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarPanel(String jogadores, boolean dono){
        comecarBotao.setVisible(dono);
        textFieldTempoDeEspera.setEnabled(dono);
        jogadoresPanel.removeAll();
        String[] linhas = jogadores.split("\\^\\^\\^"); // Divide os jogos por linha
        for (String linha : linhas) {
            JLabel label = new JLabel(linha);
            jogadoresPanel.add(label);
        }
        jogadoresPanel.revalidate();
        jogadoresPanel.repaint();
    }
    
    private void comecarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comecarBotaoActionPerformed
        MemoriaJogador memoriaJogador = menu.getMemoriaJogador();
        memoriaJogador.enviarMensagem("Começar Jogo - " + textFieldTempoDeEspera.getText());
    }//GEN-LAST:event_comecarBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comecarBotao;
    private javax.swing.JPanel jogadoresPanel;
    private javax.swing.JLabel labelTempoDeEspera;
    private javax.swing.JTextField textFieldTempoDeEspera;
    // End of variables declaration//GEN-END:variables
}
