/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my_company.memoria.jogador;

import javax.swing.JOptionPane;

/**
 *
 * @author pinhe
 */
public class Inicial extends javax.swing.JPanel {
    private MenuCliente menu;
    
    /**
     * Creates new form Inicial
     */
    public Inicial(MenuCliente menu) {
        this.menu = menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoJogar = new javax.swing.JButton();
        botaoVer = new javax.swing.JButton();

        botaoJogar.setText("Conectar Para Jogar");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        botaoVer.setText("Conectar Para Ver");
        botaoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botaoJogar)
                .addGap(18, 18, 18)
                .addComponent(botaoVer)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
        MemoriaJogador memoriaJogador = menu.getMemoriaJogador();
        if (memoriaJogador.conectarAoServidor("127.0.0.1", 6666)) {
            JOptionPane.showMessageDialog(null, "Conectado!");
            menu.trocarPainel("EntrarJogo");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao conectar!");
        }
    }//GEN-LAST:event_botaoJogarActionPerformed

    private void botaoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerActionPerformed
        MemoriaTelespectador memoriaTelespectador = menu.getMemoriaTelespectador();
        if (memoriaTelespectador.conectar()) {
            menu.trocarPainel("EntrarJogo");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao conectar!");
        }
    }//GEN-LAST:event_botaoVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoJogar;
    private javax.swing.JButton botaoVer;
    // End of variables declaration//GEN-END:variables
}
